### ISSUE TITLE
All tech paths lead to stargates

### ISSUE THREAD

**Issue by ekolis** [ekolis/stars-nova#18]
**Describe the bug**
I started a new game (default settings) and when I look at the research screen all I see as expected results is a bunch of stargates.

**To Reproduce**
1. Start a new game with the default settings.
2. Open the research screen.

**Expected behavior**
Clicking a tech area shows what I can unlock by researching it.

**Actual behavior**
Clicking a tech area shows a bunch of stargates as expected results, or nothing at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/2612506/80781243-b2f7b480-8b3f-11ea-8c80-38c655c55542.png)

**Additional context**

**Comment by marhawkman** [comment]
Yeah "expected" research benefits screen being jacked up is something I've been wanted to file a report about but I can't seem to figure out WHAT to say other than "it's not working right"...

Sometimes it'll show you a huge list of stuff, other times nothing, but never the actual results of gaining the next level.

**Comment by ekolis** [comment]
I think there's a bug in the code that handles tech requirements. I wrote some unit tests to see what exactly is going on, but I'm having trouble running the tests; I keep getting errors in the output window and the tests never run. I pushed a branch for this issue in case anyone wants to look at it...

**Comment by marhawkman** [comment]
I wonder if this might be related to the bug with racial tech being sometimes available to other races?

In my current test game I'm playing Inner Strength  I can use in designs: Depleted Neutronium(Super Stealth), Orbital adjustors(Claim Adjustor), Heavy Mines(Space Demolition), Stargate Any/300(Interstellar Traveller).  Also I don't have advanced remote mining or improved starbases but have those techs available anyways.

**Comment by ekolis** [comment]
Yeah, the tech requirements code doesn't seem to be taking into account racial traits, either. I'll have to add that in once I get this issue taken care of.

**Comment by ekolis** [comment]
(I actually discovered this bug while attempting to investigate the racial tech one! 😉)

**Comment by ekolis** [comment]
Should be fixed now!
