### ISSUE TITLE
Modernized GUI

### ISSUE THREAD

**Issue by ekolis** [ekolis/stars-nova#58]
**Describe the feature you'd like to see**
Replace the WinForms GUI with something more modern.

**Benefits**
The GUI will look nicer, it will be easier to style it and use modern UI conventions, and we might even be able to add support for additional platforms such as Android by using certain frameworks.

**Describe alternatives**
Some possibilities:
* WPF - kind of outdated, limited to Windows
* UWP - somewhat outdated, limited to Windows 10
* Avalonia - cross platform but designer support is lacking last I checked
* Unity - very powerful and cross platform but it will take some getting used to
* Xamarin - cross platform, might be obsolete now that we have MAUI
* MAUI - cross platform but I seem to recall it doesn't work on Linux even though it supports Android, go figure...

**Additional context**
blah blah

**Comment by marhawkman** [comment]
hmmm the UI definitely had room for improvements!

**Comment by ekolis** [comment]
Duplicate of #51
